<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="48175" started-at="2019-06-13T08:47:18Z" finished-at="2019-06-13T08:48:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="48175" started-at="2019-06-13T08:47:18Z" finished-at="2019-06-13T08:48:07Z">
      <class name="alpha.Testcase">
        <test-method status="FAIL" signature="Quitbowser()[pri:0, instance:alpha.Testcase@3e58a80e]" name="Quitbowser" duration-ms="14" started-at="2019-06-13T08:47:18Z" finished-at="2019-06-13T08:47:18Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at alpha.Testcase.Quitbowser(Testcase.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Quitbowser -->
        <test-method status="PASS" signature="launchDriver()[pri:1, instance:alpha.Testcase@3e58a80e]" name="launchDriver" duration-ms="41033" started-at="2019-06-13T08:47:18Z" finished-at="2019-06-13T08:48:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method status="PASS" signature="selectFromplace()[pri:2, instance:alpha.Testcase@3e58a80e]" name="selectFromplace" duration-ms="2495" started-at="2019-06-13T08:48:00Z" finished-at="2019-06-13T08:48:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectFromplace -->
        <test-method status="PASS" signature="selectToplace()[pri:3, instance:alpha.Testcase@3e58a80e]" name="selectToplace" duration-ms="2426" started-at="2019-06-13T08:48:02Z" finished-at="2019-06-13T08:48:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectToplace -->
        <test-method status="PASS" signature="selectdate()[pri:4, instance:alpha.Testcase@3e58a80e]" name="selectdate" duration-ms="2122" started-at="2019-06-13T08:48:04Z" finished-at="2019-06-13T08:48:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectdate -->
      </class> <!-- alpha.Testcase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
